#!/bin/bash

#SBATCH --partition=gpu_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=evaluate-doc-embeddings
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --time=1:00:00
#SBATCH --mem=48000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

# Job starts in the directory where you call sbatch
cd ~/mscai-ir2/

# Activate environment
source activate mscai-ir2

# Run
srun python3 score_aggregation.py